'''
Module for ZEN-based predictive signal generation.

This module uses the image generation pipeline to create visualizations
based on market data and then interprets these visualizations to derive
trading signals.
'''
import torch
from PIL import Image, ImageStat
import pandas as pd
import numpy as np
import logging

# Configure logging for this module
logger = logging.getLogger(__name__)

# Attempt to import flux.generate, relying on sys.path modification by the caller (gradio_app.py)
try:
    from flux.generate import generate as flux_generate_func
except ImportError:
    flux_generate_func = None
    logger.warning("flux.generate could not be imported in zen_predictor.py. ZEN image generation will be disabled.")

# Global placeholder for the initialized pipeline instance (can be used by other functions if needed)
_pipeline = None

def initialize_zen_predictor(pipeline_instance):
    """
    Initializes the ZEN predictor with the main image generation pipeline.
    This allows other functions in this module to potentially use a globally set pipeline.
    For the backtesting flow via get_zen_signal, the pipeline is passed explicitly.

    Args:
        pipeline_instance: The initialized FluxPipeline object.
    """
    global _pipeline
    _pipeline = pipeline_instance
    if _pipeline is not None:
        logger.info("ZEN Predictor globally initialized with pipeline.")
    else:
        logger.warning("ZEN Predictor globally initialized with a None pipeline.")

def construct_prompt_for_zen(current_market_data: pd.DataFrame, historical_data_summary: pd.Series, base_prompt: str, strategy_params: dict = None) -> str:
    """
    Constructs a text prompt for the ZEN image generation model
    based on current market data, historical summary, a base user prompt, and strategy parameters.

    Args:
        current_market_data (pd.DataFrame): Slice of recent market data (OHLCV).
        historical_data_summary (pd.Series): Summary statistics of the entire historical dataset.
        base_prompt (str): A user-defined base prompt.
        strategy_params (dict, optional): Parameters of the trading strategy.

    Returns:
        str: A text prompt for the ZEN model.
    """
    if strategy_params is None:
        strategy_params = {}

    prompt_parts = [base_prompt]

    # Details from current_market_data (the slice)
    if not current_market_data.empty:
        latest_close = current_market_data['close'].iloc[-1]
        latest_volume = current_market_data['volume'].iloc[-1]
        prompt_parts.append(f"Current market: Price={latest_close:.2f}, Volume={latest_volume:.0f}.")

        if len(current_market_data) > 1:
            prev_close = current_market_data['close'].iloc[-2]
            price_change = latest_close - prev_close
            trend_direction = "upward" if price_change > 0 else "downward" if price_change < 0 else "stable"
            prompt_parts.append(f"Short-term trend: {trend_direction} ({price_change:+.2f}).")
        
        avg_slice_vol = current_market_data['volume'].mean()
        prompt_parts.append(f"Recent average volume: {avg_slice_vol:.0f}.")

    # Details from historical_data_summary
    summary_desc = []
    if 'close_mean' in historical_data_summary:
        summary_desc.append(f"AvgPrice={historical_data_summary['close_mean']:.2f}")
    if 'close_std' in historical_data_summary:
        summary_desc.append(f"Volatility(StdDev)={historical_data_summary['close_std']:.2f}")
    if 'total_period_return' in historical_data_summary:
        summary_desc.append(f"TotalReturn={historical_data_summary['total_period_return']:.2%}")
    if summary_desc:
        prompt_parts.append(f"Historical context: {', '.join(summary_desc)}.")

    # Details from strategy_params
    asset_name = strategy_params.get('asset', 'the asset') # Assuming 'asset' might be in params
    prompt_parts.append(f"Focus: {asset_name}.")
    
    # Combine into a single prompt string
    final_prompt = " ".join(prompt_parts)
    logger.debug(f"Constructed ZEN prompt: {final_prompt}")
    return final_prompt

def analyze_zen_image_to_signal(image: Image.Image) -> float:
    """
    Analyzes the generated ZEN image to extract a trading signal.
    Placeholder implementation: uses average brightness.

    Args:
        image (PIL.Image.Image): The image generated by the ZEN model.

    Returns:
        float: A trading signal between -1.0 (strong sell) and 1.0 (strong buy).
               Returns 0.0 if image is None.
    """
    if image is None:
        logger.warning("analyze_zen_image_to_signal received None image. Returning neutral signal.")
        return 0.0

    try:
        gs_image = image.convert("L")  # Convert to grayscale
        pixels = np.array(gs_image)
        avg_intensity = np.mean(pixels)  # Average pixel intensity (0-255)

        # Normalize to -1.0 to 1.0 (127.5 is neutral 0.0)
        signal = (avg_intensity / 127.5) - 1.0
        signal = np.clip(signal, -1.0, 1.0) # Ensure it's within bounds
        
        logger.debug(f"ZEN image analysis: avg_intensity={avg_intensity:.2f}, signal={signal:.4f}")
        return float(signal)
    except Exception as e:
        logger.error(f"Error during ZEN image analysis: {e}. Returning neutral signal.")
        return 0.0

def get_zen_signal(current_market_data: pd.Series, 
                   historical_data_summary: pd.DataFrame, 
                   optional_prompt_elements: str = "") -> float:
    """
    Generates a predictive signal using ZEN's image generation and analysis capabilities.

    Args:
        current_market_data: DataFrame row or dict for the current timestep.
        historical_data_summary: A small window of past prices, volumes, or LeniaOODA indicator states.
        optional_prompt_elements: User-defined text or parameters to guide image generation.

    Returns:
        A normalized signal (e.g., -1.0 for strong sell, 0.0 for neutral, 1.0 for strong buy).
    """
    print(f"ZEN_PREDICTOR: Received current_market_data:\n{current_market_data}")
    print(f"ZEN_PREDICTOR: Received historical_data_summary:\n{historical_data_summary.head()}")
    print(f"ZEN_PREDICTOR: Received optional_prompt_elements: {optional_prompt_elements}")

    # 1. Construct a prompt for flux.generate.generate
    prompt = f"Analyze market sentiment based on current price {current_market_data.get('close', 'N/A')} "
    prompt += f"and recent historical trends. {optional_prompt_elements}"
    print(f"ZEN_PREDICTOR: Constructed prompt: {prompt}")

    # 2. Simulate image generation and analysis
    simulated_image_analysis_outcome = "bullish"  # Simulated outcome

    # 3. Image-to-Signal Conversion
    signal = 0.0
    if simulated_image_analysis_outcome == "bullish":
        signal = 0.75
    elif simulated_image_analysis_outcome == "bearish":
        signal = -0.75
    else:
        signal = 0.0
    print(f"ZEN_PREDICTOR: Simulated image analysis outcome: {simulated_image_analysis_outcome}, Signal: {signal}")

    # 4. Return a normalized signal
    return signal

if __name__ == '__main__':
    # Example Usage (for testing this module standalone)
    print("ZEN_PREDICTOR: Running standalone test...")
    dummy_current_data = pd.Series({
        'timestamp': pd.Timestamp('2025-05-13 10:00:00'),
        'open': 100,
        'high': 105,
        'low': 98,
        'close': 102,
        'volume': 1000
    })
    dummy_historical_data = pd.DataFrame({
        'timestamp': pd.to_datetime(['2025-05-13 09:55:00', '2025-05-13 09:50:00']),
        'open': [98, 95],
        'high': [100, 97],
        'low': [97, 94],
        'close': [99, 96],
        'volume': [800, 700]
    })
    dummy_prompt_elements = "Focus on short-term volatility."

    zen_signal = get_zen_signal(dummy_current_data, dummy_historical_data, dummy_prompt_elements)
    print(f"ZEN_PREDICTOR: Standalone test - Received ZEN signal: {zen_signal}")
    print("ZEN_PREDICTOR: Standalone test completed.")
